### ISSUE TITLE
Lithuanian (LT) translation | RiiConnect24 Terms of Service

### ISSUE THREAD

**Issue by j2x5j** [RiiConnect24/CFH#10]
I had finally caved in and translated the whole terms of service to Lithuanian, so I wouldn't have to use the UK region on my Wii. I will be waiting for an answer, thanks!
[lt.RenameTXTtoHTML.txt](https://github.com/RiiConnect24/CFH/files/8102175/lt.RenameTXTtoHTML.txt)

P.S. I'm so sorry if I'm posting this to the wrong place, I'm new to GitHub.

**Comment by KcrPL** [comment]
Please press the "Fork" button on top right of the screen, it will create a copy of CFH repository in your account, upload your file there and make a Pull Request. We will then review it.

This also doesn't guarantee we will enable RiiConnect24 for your language. There's some additional work but we will consider it.
